# 2023-06-24 09:00
name: act - Build

on:
#  push:
#    branches:
#      - main
#    tags:
#      - v0.*
#  pull_request:
  workflow_dispatch:
    inputs:
      # if: ${{ inputs.build_release_windows }}
      build_release_windows:
        description: Build release Windows
        type: boolean
        required: true
        default: true
      # if: ${{ inputs.build_release_ubuntu }}
      build_release_ubuntu:
        description: Build release Ubuntu
        type: boolean
        required: true
        default: true
      # if: ${{ inputs.build_and_test }}
      build_and_test:
        description: Build and test
        type: boolean
        required: true
        default: false
      # if: ${{ inputs.rustfmt }}
      rustfmt:
        description: rustfmt
        type: boolean
        required: true
        default: false
      # if: ${{ inputs.clippy }}
      clippy:
        description: clippy
        type: boolean
        required: true
        default: false

env:
  CARGO_INCREMENTAL: 0
  TAG_NAME: "presage"
  VERSION: "v.0.5.3"
  DEBUG_LS: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_release_windows:
    name: cargo build release windows
    if: ${{ inputs.build_release_windows }}
    runs-on: windows-2019
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Configure CI cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-pc-windows-msvc --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target x86_64-pc-windows-msvc --release

###
# zip release begin
      - name: Create Archive Release
        uses: deep-soft/zip-release@v2
        with:
          type: 'zip'
          filename: '${{ env.TAG_NAME }}-${{ env.VERSION }}.zip'
          directory: '.'
          path: '.'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: print env value
        shell: bash
        run: |
          echo "env.ZIP_RELEASE_ARCHIVE=${{ env.ZIP_RELEASE_ARCHIVE }}"

      - name: Publish Release
        continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ github.job }}-windows
          files: |
            ${{ env.ASSET_REL }}
            ${{ env.ZIP_RELEASE_ARCHIVE }}
# zip release end

  build_release_ubuntu:
    name: cargo build release ubuntu
    if: ${{ inputs.build_release_ubuntu }}
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Configure CI cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-linux-gnu --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target x86_64-unknown-linux-gnu --release

###
# zip release begin
      - name: Create Archive Release
        uses: deep-soft/zip-release@v2
        with:
          type: 'zip'
          filename: '${{ env.TAG_NAME }}-${{ env.VERSION }}.zip'
          directory: '.'
          path: '.'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: print env value
        shell: bash
        run: |
          echo "env.ZIP_RELEASE_ARCHIVE=${{ env.ZIP_RELEASE_ARCHIVE }}"

      - name: Publish Release
        continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ github.job }}-ubuntu
          files: |
            ${{ env.ASSET_REL }}
            ${{ env.ZIP_RELEASE_ARCHIVE }}
# zip release end

  build_and_test:
    name: cargo build
    if: ${{ inputs.build_and_test }}
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Configure CI cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets

  rustfmt:
    name: rustfmt
    if: ${{ inputs.rustfmt }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      
      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: clippy
    if: ${{ inputs.clippy }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      
      - name: Setup CI cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
